import './globals.css'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import { Nunito, Plus_Jakarta_Sans } from 'next/font/google'
import { Providers } from './provider'
import { auth } from 'auth'
import { SessionProvider } from 'next-auth/react'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
})

const jakarta = Plus_Jakarta_Sans({
  variable: '--font-jakarta',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={cn('antialiased', nunito.variable, jakarta.variable)}>
        <SessionProvider session={session}>
          <Providers
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange={false}
          >
            <main className="font-nunito">{children}</main>
          </Providers>
          <Toaster position="bottom-right" richColors />
        </SessionProvider>
      </body>
    </html>
  )
}
